language: php

dist: trusty

sudo: false

php:
  - 7.1
  - 7.2

before_install:
  - travis_retry composer self-update

before_script:
  - travis_wait composer install --dev --prefer-source

script: ./bin/phpunit

notifications:
  email: false